name: flutter_izipay_example
description: "Demonstrates how to use the flutter_izipay plugin."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_izipay:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  very_good_analysis: 6.0.0

flutter:
  uses-material-design: true
